name: mdbook to pages

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

defaults:
  run:
    shell: bash
    working-directory: ./book

jobs:
  link_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.6.1
        with:
          args: --verbose --no-progress --exclude-link-local --exclude-loopback --exclude-mail ./README.md ./book/src
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build_and_deploy:
    needs: link_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - name: Build
        run: mdbook build

      - name: Set CNAME
        run: cp ../CNAME ./book/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book
