name: mdbook to pages

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

defaults:
  run:
    shell: bash
    working-directory: ./book

jobs:
  link_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.3.2
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        if: ${{ steps.lychee.outputs.exit_code }} != 0
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue

  build_and_deploy:
    needs: link_check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1.1.14
        with:
          mdbook-version: 'latest'

      - name: Build
        run: mdbook build

      - name: Set CNAME
        run: cp ../CNAME ./book/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./book/book
